### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mattiasw2** [emil0r/reverie#35]
Followed the instructions at 

      https://github.com/emil0r/reverie/blob/master/doc/installation/getting-started.md 

but already got lost on the first row since there is no published version of 

      [reverie/lein-template "1.2.0"].

Changed to 

       [reverie/lein-template "1.1-alpha1"] 

but just got a vanilla clojure app.

Do you have a zip-file of the initial project?

**Comment by emil0r** [comment]
I'm having trouble publishing to clojars right now. Pushed the 1.2.0 to github, so one option is to clone the reverie-template repo locally, install with leiningen and then continue with the list.

Haven't had any time to polish the install process, so I would highly value feedback on it.

**Comment by mattiasw2** [comment]
First time I use lein where plugin doesn't exist in clojar, so I think I need some more instructions.

I first moved the /.lein/profiles.clj file away. Just to make sure nothing else interferes.

```
git clone https://github.com/emil0r/reverie-template.git
cd reverie-template/
lein install
```

and got

```
Created c:\data-oss\clojure\reverie-template\target\lein-template-1.2.0.jar
Wrote c:\data-oss\clojure\reverie-template\pom.xml
Installed jar and pom into local repo.
```

I created a .lein/profiles file whose only contents is

```
{:user {:plugins [[reverie/lein-template "1.2.0"]]}}
```

Now, I run
```
lein new reverie
```

but the result was a completely vanilla clojure project called reverie with no references to reverie. What did I miss?

**Comment by mattiasw2** [comment]
I am on Windows 10.

**Comment by emil0r** [comment]
Try lein new reverie <project-name>

**Comment by mattiasw2** [comment]
lein new reverie myrev

worked, but then I got this following error.

I have a # in my postgresql password, otherwise, everything is plain.

```
c:\data4\clojure\reverie\myrev>lein run :command :init
Retrieving reverie-core/reverie-core/0.8.0/reverie-core-0.8.0.pom from clojars
Retrieving org/clojure/core.match/0.2.2/core.match-0.2.2.pom from central
Retrieving org/clojure/tools.analyzer.jvm/0.1.0-beta12/tools.analyzer.jvm-0.1.0-beta12.pom from central
Retrieving org/clojure/tools.analyzer/0.1.0-beta12/tools.analyzer-0.1.0-beta12.pom from central
Retrieving org/ow2/asm/asm-all/4.1/asm-all-4.1.pom from central
Retrieving org/ow2/asm/asm-parent/4.1/asm-parent-4.1.pom from central
Retrieving org/clojure/core.async/0.1.267.0-0d7780-alpha/core.async-0.1.267.0-0d7780-alpha.pom from central
Retrieving com/stuartsierra/component/0.2.3/component-0.2.3.pom from clojars
Retrieving com/stuartsierra/dependency/0.1.1/dependency-0.1.1.pom from clojars
Retrieving vlad/vlad/3.3.0/vlad-3.3.0.pom from clojars
Retrieving ez-web/ez-web/0.3.0/ez-web-0.3.0.pom from clojars
Retrieving ez-image/ez-image/1.0.4/ez-image-1.0.4.pom from clojars
Retrieving digest/digest/1.4.4/digest-1.4.4.pom from clojars
Retrieving org/imgscalr/imgscalr-lib/4.2/imgscalr-lib-4.2.pom from central
Retrieving ez-email/ez-email/0.1.0/ez-email-0.1.0.pom from clojars
Retrieving org/clojure/core.async/0.2.391/core.async-0.2.391.pom from central
Retrieving com/draines/postal/2.0.0/postal-2.0.0.pom from clojars
Retrieving com/sun/mail/javax.mail/1.5.5/javax.mail-1.5.5.pom from central
Retrieving com/sun/mail/all/1.5.5/all-1.5.5.pom from central
Retrieving net/java/jvnet-parent/1/jvnet-parent-1.pom from central
Retrieving javax/activation/activation/1.1/activation-1.1.pom from central
Retrieving javax/mail/javax.mail-api/1.5.5/javax.mail-api-1.5.5.pom from central
Retrieving bultitude/bultitude/0.2.8/bultitude-0.2.8.pom from clojars
Retrieving slingshot/slingshot/0.12.2/slingshot-0.12.2.pom from clojars
Retrieving buddy/buddy-core/0.9.0/buddy-core-0.9.0.pom from clojars
Retrieving org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.pom from central
Retrieving org/bouncycastle/bcpkix-jdk15on/1.54/bcpkix-jdk15on-1.54.pom from central
Retrieving buddy/buddy-hashers/0.11.0/buddy-hashers-0.11.0.pom from clojars
Retrieving buddy/buddy-auth/0.9.0/buddy-auth-0.9.0.pom from clojars
Retrieving buddy/buddy-sign/0.9.0/buddy-sign-0.9.0.pom from clojars
Retrieving com/taoensso/nippy/2.10.0/nippy-2.10.0.pom from clojars
Retrieving com/taoensso/encore/2.18.0/encore-2.18.0.pom from clojars
Retrieving org/iq80/snappy/snappy/0.4/snappy-0.4.pom from central
Retrieving net/jpountz/lz4/lz4/1.3/lz4-1.3.pom from central
Retrieving funcool/cuerdas/0.7.1/cuerdas-0.7.1.pom from clojars
Retrieving com/taoensso/tower/3.0.2/tower-3.0.2.pom from clojars
Retrieving com/taoensso/encore/1.10.2/encore-1.10.2.pom from clojars
Retrieving org/clojure/tools.reader/0.8.9/tools.reader-0.8.9.pom from central
Retrieving com/taoensso/timbre/3.3.1/timbre-3.3.1.pom from clojars
Retrieving com/taoensso/encore/1.8.1/encore-1.8.1.pom from clojars
Retrieving org/clojure/tools.reader/0.8.8/tools.reader-0.8.8.pom from central
Retrieving io/aviso/pretty/0.1.12/pretty-0.1.12.pom from clojars
Retrieving markdown-clj/markdown-clj/0.9.54/markdown-clj-0.9.54.pom from clojars
Retrieving im/chit/cronj/1.4.3/cronj-1.4.3.pom from clojars
Retrieving org/clojure/tools.logging/0.3.0/tools.logging-0.3.0.pom from central
Retrieving clj-time/clj-time/0.8.0/clj-time-0.8.0.pom from clojars
Retrieving im/chit/hara.common.primitives/2.1.5/hara.common.primitives-2.1.5.pom from clojars
Retrieving im/chit/hara.common.error/2.1.5/hara.common.error-2.1.5.pom from clojars
Retrieving im/chit/hara.common.checks/2.1.5/hara.common.checks-2.1.5.pom from clojars
Retrieving im/chit/hara.namespace.import/2.1.5/hara.namespace.import-2.1.5.pom from clojars
Retrieving im/chit/hara.ova/2.1.5/hara.ova-2.1.5.pom from clojars
Retrieving im/chit/hara.common.watch/2.1.5/hara.common.watch-2.1.5.pom from clojars
Retrieving im/chit/hara.protocol.watch/2.1.5/hara.protocol.watch-2.1.5.pom from clojars
Retrieving im/chit/hara.expression.shorthand/2.1.5/hara.expression.shorthand-2.1.5.pom from clojars
Retrieving im/chit/hara.namespace.resolve/2.1.5/hara.namespace.resolve-2.1.5.pom from clojars
Retrieving im/chit/hara.function.dispatch/2.1.5/hara.function.dispatch-2.1.5.pom from clojars
Retrieving im/chit/hara.function.args/2.1.5/hara.function.args-2.1.5.pom from clojars
Retrieving im/chit/hara.common.hash/2.1.5/hara.common.hash-2.1.5.pom from clojars
Retrieving im/chit/hara.common.state/2.1.5/hara.common.state-2.1.5.pom from clojars
Retrieving im/chit/hara.protocol.state/2.1.5/hara.protocol.state-2.1.5.pom from clojars
Retrieving im/chit/hara.concurrent.latch/2.1.5/hara.concurrent.latch-2.1.5.pom from clojars
Retrieving prismatic/schema/1.1.0/schema-1.1.0.pom from clojars
Retrieving reverie-sql/reverie-sql/0.8.0/reverie-sql-0.8.0.pom from clojars
Retrieving org/clojure/java.jdbc/0.4.1/java.jdbc-0.4.1.pom from central
Retrieving honeysql/honeysql/0.6.3/honeysql-0.6.3.pom from clojars
Retrieving yesql/yesql/0.5.2/yesql-0.5.2.pom from clojars
Retrieving org/clojure/java.jdbc/0.4.2/java.jdbc-0.4.2.pom from central
Retrieving instaparse/instaparse/1.4.1/instaparse-1.4.1.pom from clojars
Retrieving ez-database/ez-database/0.5.3/ez-database-0.5.3.pom from clojars
Retrieving honeysql/honeysql/0.6.1/honeysql-0.6.1.pom from clojars
Retrieving ez-form/ez-form/0.7.0/ez-form-0.7.0.pom from clojars
Retrieving joplin/jdbc/joplin.jdbc/0.3.4/joplin.jdbc-0.3.4.pom from clojars
Retrieving joplin/core/joplin.core/0.3.4/joplin.core-0.3.4.pom from clojars
Retrieving ragtime/ragtime.core/0.5.1/ragtime.core-0.5.1.pom from clojars
Retrieving ragtime/ragtime.jdbc/0.5.1/ragtime.jdbc-0.5.1.pom from clojars
Retrieving org/clojure/java.jdbc/0.3.7/java.jdbc-0.3.7.pom from central
Retrieving resauce/resauce/0.1.0/resauce-0.1.0.pom from clojars
Retrieving hikari-cp/hikari-cp/1.6.1/hikari-cp-1.6.1.pom from clojars
Retrieving com/zaxxer/HikariCP/2.4.3/HikariCP-2.4.3.pom from central
Retrieving org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom from central
Retrieving org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom from central
Retrieving http-kit/http-kit/2.1.19/http-kit-2.1.19.pom from clojars
Retrieving org/postgresql/postgresql/9.2-1002-jdbc4/postgresql-9.2-1002-jdbc4.pom from central
Retrieving org/clojure/core.match/0.2.2/core.match-0.2.2.jar from central
Retrieving org/clojure/tools.analyzer.jvm/0.1.0-beta12/tools.analyzer.jvm-0.1.0-beta12.jar from central
Retrieving org/ow2/asm/asm-all/4.1/asm-all-4.1.jar from central
Retrieving org/clojure/tools.analyzer/0.1.0-beta12/tools.analyzer-0.1.0-beta12.jar from central
Retrieving org/clojure/core.async/0.1.267.0-0d7780-alpha/core.async-0.1.267.0-0d7780-alpha.jar from central
Retrieving commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar from central
Retrieving org/clojure/clojurescript/0.0-3308/clojurescript-0.0-3308.jar from central
Retrieving com/google/javascript/closure-compiler/v20150505/closure-compiler-v20150505.jar from central
Retrieving com/google/javascript/closure-compiler-externs/v20150505/closure-compiler-externs-v20150505.jar from central
Retrieving com/google/guava/guava/18.0/guava-18.0.jar from central
Retrieving args4j/args4j/2.0.26/args4j-2.0.26.jar from central
Retrieving com/google/code/gson/gson/2.2.4/gson-2.2.4.jar from central
Retrieving com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar from central
Retrieving org/clojure/google-closure-library-third-party/0.0-20150505-021ed5b3/google-closure-library-third-party-0.0-20150505-021ed5b3.jar from central
Retrieving org/clojure/google-closure-library/0.0-20150505-021ed5b3/google-closure-library-0.0-20150505-021ed5b3.jar from central
Retrieving com/fasterxml/jackson/core/jackson-core/2.4.4/jackson-core-2.4.4.jar from central
Retrieving com/cognitect/transit-clj/0.8.269/transit-clj-0.8.269.jar from central
Retrieving com/fasterxml/jackson/datatype/jackson-datatype-json-org/2.3.2/jackson-datatype-json-org-2.3.2.jar from central
Retrieving com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar from central
Retrieving com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.jar from central
Retrieving com/cognitect/transit-java/0.8.276/transit-java-0.8.276.jar from central
Retrieving org/apache/directory/studio/org.apache.commons.codec/1.8/org.apache.commons.codec-1.8.jar from central
Retrieving org/imgscalr/imgscalr-lib/4.2/imgscalr-lib-4.2.jar from central
Retrieving joda-time/joda-time/2.8.2/joda-time-2.8.2.jar from central
Retrieving com/sun/mail/javax.mail/1.5.5/javax.mail-1.5.5.jar from central
Retrieving javax/activation/activation/1.1/activation-1.1.jar from central
Retrieving javax/mail/javax.mail-api/1.5.5/javax.mail-api-1.5.5.jar from central
Retrieving org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar from central
Retrieving org/bouncycastle/bcpkix-jdk15on/1.54/bcpkix-jdk15on-1.54.jar from central
Retrieving net/jpountz/lz4/lz4/1.3/lz4-1.3.jar from central
Retrieving org/iq80/snappy/snappy/0.4/snappy-0.4.jar from central
Retrieving org/clojure/tools.logging/0.3.0/tools.logging-0.3.0.jar from central
Retrieving org/clojure/java.jdbc/0.4.1/java.jdbc-0.4.1.jar from central
Retrieving com/zaxxer/HikariCP/2.4.3/HikariCP-2.4.3.jar from central
Retrieving org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar from central
Retrieving org/postgresql/postgresql/9.2-1002-jdbc4/postgresql-9.2-1002-jdbc4.jar from central
Retrieving com/stuartsierra/dependency/0.1.1/dependency-0.1.1.jar from clojars
Retrieving ring/ring-anti-forgery/1.0.0/ring-anti-forgery-1.0.0.jar from clojars
Retrieving ring/ring-codec/1.0.0/ring-codec-1.0.0.jar from clojars
Retrieving reverie-core/reverie-core/0.8.0/reverie-core-0.8.0.jar from clojars
Retrieving ring/ring-core/1.4.0/ring-core-1.4.0.jar from clojars
Retrieving com/stuartsierra/component/0.2.3/component-0.2.3.jar from clojars
Retrieving vlad/vlad/3.3.0/vlad-3.3.0.jar from clojars
Retrieving ring/ring-defaults/0.1.2/ring-defaults-0.1.2.jar from clojars
Retrieving ring/ring-headers/0.1.1/ring-headers-0.1.1.jar from clojars
Retrieving ring/ring-devel/1.3.2/ring-devel-1.3.2.jar from clojars
Retrieving clj-stacktrace/clj-stacktrace/0.2.7/clj-stacktrace-0.2.7.jar from clojars
Retrieving ns-tracker/ns-tracker/0.2.2/ns-tracker-0.2.2.jar from clojars
Retrieving compojure/compojure/1.3.3/compojure-1.3.3.jar from clojars
Retrieving medley/medley/0.5.5/medley-0.5.5.jar from clojars
Retrieving ez-web/ez-web/0.3.0/ez-web-0.3.0.jar from clojars
Retrieving ez-image/ez-image/1.0.4/ez-image-1.0.4.jar from clojars
Retrieving ez-email/ez-email/0.1.0/ez-email-0.1.0.jar from clojars
Retrieving com/draines/postal/2.0.0/postal-2.0.0.jar from clojars
Retrieving bultitude/bultitude/0.2.8/bultitude-0.2.8.jar from clojars
Retrieving slingshot/slingshot/0.12.2/slingshot-0.12.2.jar from clojars
Retrieving buddy/buddy-core/0.9.0/buddy-core-0.9.0.jar from clojars
Retrieving buddy/buddy-hashers/0.11.0/buddy-hashers-0.11.0.jar from clojars
Retrieving buddy/buddy-auth/0.9.0/buddy-auth-0.9.0.jar from clojars
Retrieving buddy/buddy-sign/0.9.0/buddy-sign-0.9.0.jar from clojars
Retrieving com/taoensso/nippy/2.10.0/nippy-2.10.0.jar from clojars
Retrieving funcool/cuerdas/0.7.1/cuerdas-0.7.1.jar from clojars
Retrieving digest/digest/1.4.4/digest-1.4.4.jar from clojars
Retrieving com/taoensso/truss/1.3.5/truss-1.3.5.jar from clojars
Retrieving com/taoensso/tower/3.0.2/tower-3.0.2.jar from clojars
Retrieving markdown-clj/markdown-clj/0.9.54/markdown-clj-0.9.54.jar from clojars
Retrieving im/chit/cronj/1.4.3/cronj-1.4.3.jar from clojars
Retrieving im/chit/hara.common.primitives/2.1.5/hara.common.primitives-2.1.5.jar from clojars
Retrieving im/chit/hara.common.error/2.1.5/hara.common.error-2.1.5.jar from clojars
Retrieving im/chit/hara.common.checks/2.1.5/hara.common.checks-2.1.5.jar from clojars
Retrieving im/chit/hara.namespace.import/2.1.5/hara.namespace.import-2.1.5.jar from clojars
Retrieving im/chit/hara.ova/2.1.5/hara.ova-2.1.5.jar from clojars
Retrieving im/chit/hara.common.watch/2.1.5/hara.common.watch-2.1.5.jar from clojars
Retrieving im/chit/hara.protocol.watch/2.1.5/hara.protocol.watch-2.1.5.jar from clojars
Retrieving im/chit/hara.common.hash/2.1.5/hara.common.hash-2.1.5.jar from clojars
Retrieving im/chit/hara.common.state/2.1.5/hara.common.state-2.1.5.jar from clojars
Retrieving im/chit/hara.protocol.state/2.1.5/hara.protocol.state-2.1.5.jar from clojars
Retrieving im/chit/hara.expression.shorthand/2.1.5/hara.expression.shorthand-2.1.5.jar from clojars
Retrieving im/chit/hara.namespace.resolve/2.1.5/hara.namespace.resolve-2.1.5.jar from clojars
Retrieving im/chit/hara.function.dispatch/2.1.5/hara.function.dispatch-2.1.5.jar from clojars
Retrieving im/chit/hara.function.args/2.1.5/hara.function.args-2.1.5.jar from clojars
Retrieving im/chit/hara.concurrent.latch/2.1.5/hara.concurrent.latch-2.1.5.jar from clojars
Retrieving prismatic/schema/1.1.0/schema-1.1.0.jar from clojars
Retrieving reverie-sql/reverie-sql/0.8.0/reverie-sql-0.8.0.jar from clojars
Retrieving honeysql/honeysql/0.6.3/honeysql-0.6.3.jar from clojars
Retrieving yesql/yesql/0.5.2/yesql-0.5.2.jar from clojars
Retrieving ez-database/ez-database/0.5.3/ez-database-0.5.3.jar from clojars
Retrieving ez-form/ez-form/0.7.0/ez-form-0.7.0.jar from clojars
Retrieving joplin/jdbc/joplin.jdbc/0.3.4/joplin.jdbc-0.3.4.jar from clojars
Retrieving joplin/core/joplin.core/0.3.4/joplin.core-0.3.4.jar from clojars
Retrieving ragtime/ragtime.core/0.5.1/ragtime.core-0.5.1.jar from clojars
Retrieving ragtime/ragtime.jdbc/0.5.1/ragtime.jdbc-0.5.1.jar from clojars
Retrieving resauce/resauce/0.1.0/resauce-0.1.0.jar from clojars
Retrieving hikari-cp/hikari-cp/1.6.1/hikari-cp-1.6.1.jar from clojars
Retrieving http-kit/http-kit/2.1.19/http-kit-2.1.19.jar from clojars
Exception in thread "main" java.util.regex.PatternSyntaxException: Unclosed character class near index 9
([^\]*)\?$
         ^, compiling:(ragtime/jdbc.clj:83:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at joplin.jdbc.database$eval22653$loading__5569__auto____22654.invoke(database.clj:1)
        at joplin.jdbc.database$eval22653.invokeStatic(database.clj:1)
        at joplin.jdbc.database$eval22653.invoke(database.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:3894)
        at reverie.database.sql$eval21884$loading__5569__auto____21885.invoke(sql.clj:1)
        at reverie.database.sql$eval21884.invokeStatic(sql.clj:1)
        at reverie.database.sql$eval21884.invoke(sql.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at myrev.command$eval26$loading__5569__auto____27.invoke(command.clj:1)
        at myrev.command$eval26.invokeStatic(command.clj:1)
        at myrev.command$eval26.invoke(command.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at myrev.core$eval20$loading__5569__auto____21.invoke(core.clj:1)
        at myrev.core$eval20.invokeStatic(core.clj:1)
        at myrev.core$eval20.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.loadResourceScript(RT.java:363)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval5$fn__7.invoke(form-init8160305266944107193.clj:1)
        at user$eval5.invokeStatic(form-init8160305266944107193.clj:1)
        at user$eval5.invoke(form-init8160305266944107193.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 9
([^\]*)\?$
         ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.clazz(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.group0(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at clojure.core$re_pattern.invokeStatic(core.clj:4665)
        at clojure.core$re_pattern.invoke(core.clj:4657)
        at ragtime.jdbc$eval22780.invokeStatic(jdbc.clj:83)
        at ragtime.jdbc$eval22780.invoke(jdbc.clj:83)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 154 more

c:\data4\clojure\reverie\myrev>
```

**Comment by emil0r** [comment]
Replicating the process didn't produce any errors on my side. Can you give me a copy of the project?

**Comment by mattiasw2** [comment]
Sorry, an important informatoin was dropped.

I successfully created the project, I got the stack trace when I run

     lein run :command :init

**Comment by emil0r** [comment]
You had included it in the original copy+paste. Could install and getting it running without any problems.

**Comment by mattiasw2** [comment]
Are you really testing with these versions?

```
 :dependencies [[org.clojure/clojure "1.8.0"]
                 [reverie-core "0.8.0"]
                 [reverie-sql "0.8.0"]
                 [http-kit "2.1.19"]
                 [org.postgresql/postgresql "9.2-1002-jdbc4"]]
```
Because when I just open the project in cider and tried to load the file init.clj or core.clj I get 

```

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling joplin/jdbc/database.clj at (1:1)

             Compiler.java: 7391  clojure.lang.Compiler/load
                   RT.java:  372  clojure.lang.RT/loadResourceScript
:
:
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
                       nil:   -1  java.util.concurrent.ThreadPoolExecutor/runWorker
                       nil:   -1  java.util.concurrent.ThreadPoolExecutor$Worker/run
                       nil:   -1  java.lang.Thread/run

1. Caused by java.lang.Exception
   No namespace: ragtime.jdbc
```

so at least it seems that all dependencies are not working perfectly. I notice there are much newer versions.

**Comment by mattiasw2** [comment]
[myrev.zip](https://github.com/emil0r/reverie/files/1035496/myrev.zip)

**Comment by emil0r** [comment]
Got it up and running no problem. You probably want to remove the file. It contains your db username + pw in the dev file. Will see if I can get Windows up and running to see if it's any different there.

**Comment by mattiasw2** [comment]
Thanks, I will also try under linux.
